### ISSUE TITLE
Tailwindcss v3.2 Compatibility

### ISSUE THREAD

**Issue by sastan** [tw-in-js/twind#414]
update @twind/preset-tailwind to be compatible with tailwindcss v3.2

### List of tailwindcss PRs

not every PR may be relevant for twind - but we need to check that twind satisfies these 

- [x] Tailwind will automatically add `content: ''` (#405)
- [ ] Allow users to block generation of certain utilities ([#9812](https://github.com/tailwindlabs/tailwindcss/pull/9812))
- [x] Fix `!important` selectors not being classified as valid class inside `safelist` config ([#9791](https://github.com/tailwindlabs/tailwindcss/pull/9791))
- [x] Sort pseudo-elements ONLY after classes when using variants and `@apply` ([#9765](https://github.com/tailwindlabs/tailwindcss/pull/9765))
- [x] Exclude non-relevant selectors when generating rules with the important modifier ([#9677](https://github.com/tailwindlabs/tailwindcss/issues/9677))
- [x] Fix fractional values not being parsed properly inside arbitrary properties ([#9705](https://github.com/tailwindlabs/tailwindcss/pull/9705))
- [x] Fix incorrect selectors when using `@apply` in selectors with combinators and pseudos ([#9722](https://github.com/tailwindlabs/tailwindcss/pull/9722))
- [x] Implement the `supports` variant ([#9453](https://github.com/tailwindlabs/tailwindcss/pull/9453), [#9616](https://github.com/tailwindlabs/tailwindcss/pull/9616))
- [x] Add new `min` and `max` variants ([#9558](https://github.com/tailwindlabs/tailwindcss/pull/9558))
- [x] Add `aria-*` variants ([#9557](https://github.com/tailwindlabs/tailwindcss/pull/9557), [#9588](https://github.com/tailwindlabs/tailwindcss/pull/9588))
- [x] Add `data-*` variants ([#9559](https://github.com/tailwindlabs/tailwindcss/pull/9559), [#9588](https://github.com/tailwindlabs/tailwindcss/pull/9588))
- [x] Add `word-break: keep-all` with `break-keep` ([#9393](https://github.com/tailwindlabs/tailwindcss/pull/9393))
- [x] Add new `collapse` utility for `visibility: collapse` ([#9181](https://github.com/tailwindlabs/tailwindcss/pull/9181))
- [x] Add `fill-none` and `stroke-none` utilities ([#9403](https://github.com/tailwindlabs/tailwindcss/pull/9403))
- [x] Add `place-content-baseline` utility ([#9498](https://github.com/tailwindlabs/tailwindcss/pull/9498))
- [x] Add `place-items-baseline` and `content-baseline` utility ([#9507](https://github.com/tailwindlabs/tailwindcss/pull/9507))
- [x] Add support for configuring default `font-feature-settings` for a font family ([#9039](https://github.com/tailwindlabs/tailwindcss/pull/9039), [#9214](https://github.com/tailwindlabs/tailwindcss/pull/9214), [#9707](https://github.com/tailwindlabs/tailwindcss/pull/9707))
- [x] Add negative value support for `outline-offset` ([#9136](https://github.com/tailwindlabs/tailwindcss/pull/9136))
- [x] Allow negating utilities using min/max/clamp ([#9237](https://github.com/tailwindlabs/tailwindcss/pull/9237))
- [x] Implement fallback plugins when arbitrary values result in css from multiple plugins ([#9376](https://github.com/tailwindlabs/tailwindcss/pull/9376))
- [x] Fix ring color utility generation when using `respectDefaultRingColorOpacity` ([#9070](https://github.com/tailwindlabs/tailwindcss/pull/9070))
- [x] Remove invalid .outline-hidden utility ([#9147](https://github.com/tailwindlabs/tailwindcss/pull/9147))
- [x] Honor the `hidden` attribute on elements in preflight ([#9174](https://github.com/tailwindlabs/tailwindcss/pull/9174))
- [x] Handle variants on complex selector utilities ([#9262](https://github.com/tailwindlabs/tailwindcss/pull/9262))
- [x] Fix ordering of parallel variants ([#9282](https://github.com/tailwindlabs/tailwindcss/pull/9282))
- [x] Handle variants in utility selectors using `:where()` and `:has()` ([#9309](https://github.com/tailwindlabs/tailwindcss/pull/9309))
- [x] Improve data type analyses for arbitrary values ([#9320](https://github.com/tailwindlabs/tailwindcss/pull/9320))
